// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// densities.cpp
SEXP density_binomial(cpp11::integers x, cpp11::integers size, cpp11::doubles prob, bool log);
extern "C" SEXP _dust_density_binomial(SEXP x, SEXP size, SEXP prob, SEXP log) {
  BEGIN_CPP11
    return cpp11::as_sexp(density_binomial(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(size), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(prob), cpp11::as_cpp<cpp11::decay_t<bool>>(log)));
  END_CPP11
}
// densities.cpp
SEXP density_normal(cpp11::doubles x, cpp11::doubles mu, cpp11::doubles sd, bool log);
extern "C" SEXP _dust_density_normal(SEXP x, SEXP mu, SEXP sd, SEXP log) {
  BEGIN_CPP11
    return cpp11::as_sexp(density_normal(cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(mu), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(sd), cpp11::as_cpp<cpp11::decay_t<bool>>(log)));
  END_CPP11
}
// densities.cpp
SEXP density_negative_binomial_mu(cpp11::integers x, cpp11::doubles size, cpp11::doubles mu, bool log, bool is_float);
extern "C" SEXP _dust_density_negative_binomial_mu(SEXP x, SEXP size, SEXP mu, SEXP log, SEXP is_float) {
  BEGIN_CPP11
    return cpp11::as_sexp(density_negative_binomial_mu(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(size), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(mu), cpp11::as_cpp<cpp11::decay_t<bool>>(log), cpp11::as_cpp<cpp11::decay_t<bool>>(is_float)));
  END_CPP11
}
// densities.cpp
SEXP density_negative_binomial_prob(cpp11::integers x, cpp11::doubles size, cpp11::doubles prob, bool log);
extern "C" SEXP _dust_density_negative_binomial_prob(SEXP x, SEXP size, SEXP prob, SEXP log) {
  BEGIN_CPP11
    return cpp11::as_sexp(density_negative_binomial_prob(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(size), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(prob), cpp11::as_cpp<cpp11::decay_t<bool>>(log)));
  END_CPP11
}
// densities.cpp
SEXP density_beta_binomial(cpp11::integers x, cpp11::integers size, cpp11::doubles prob, cpp11::doubles rho, bool log);
extern "C" SEXP _dust_density_beta_binomial(SEXP x, SEXP size, SEXP prob, SEXP rho, SEXP log) {
  BEGIN_CPP11
    return cpp11::as_sexp(density_beta_binomial(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(size), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(prob), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(rho), cpp11::as_cpp<cpp11::decay_t<bool>>(log)));
  END_CPP11
}
// densities.cpp
SEXP density_poisson(cpp11::integers x, cpp11::doubles lambda, bool log);
extern "C" SEXP _dust_density_poisson(SEXP x, SEXP lambda, SEXP log) {
  BEGIN_CPP11
    return cpp11::as_sexp(density_poisson(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(x), cpp11::as_cpp<cpp11::decay_t<cpp11::doubles>>(lambda), cpp11::as_cpp<cpp11::decay_t<bool>>(log)));
  END_CPP11
}
// openmp.cpp
cpp11::writable::list cpp_openmp_info();
extern "C" SEXP _dust_cpp_openmp_info() {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_openmp_info());
  END_CPP11
}
// test_cuda_launch_control.cpp
SEXP test_cuda_pars(cpp11::sexp r_gpu_config, int n_particles, int n_particles_each, int n_state, int n_state_full, int n_shared_int, int n_shared_real, int data_size, int shared_size);
extern "C" SEXP _dust_test_cuda_pars(SEXP r_gpu_config, SEXP n_particles, SEXP n_particles_each, SEXP n_state, SEXP n_state_full, SEXP n_shared_int, SEXP n_shared_real, SEXP data_size, SEXP shared_size) {
  BEGIN_CPP11
    return cpp11::as_sexp(test_cuda_pars(cpp11::as_cpp<cpp11::decay_t<cpp11::sexp>>(r_gpu_config), cpp11::as_cpp<cpp11::decay_t<int>>(n_particles), cpp11::as_cpp<cpp11::decay_t<int>>(n_particles_each), cpp11::as_cpp<cpp11::decay_t<int>>(n_state), cpp11::as_cpp<cpp11::decay_t<int>>(n_state_full), cpp11::as_cpp<cpp11::decay_t<int>>(n_shared_int), cpp11::as_cpp<cpp11::decay_t<int>>(n_shared_real), cpp11::as_cpp<cpp11::decay_t<int>>(data_size), cpp11::as_cpp<cpp11::decay_t<int>>(shared_size)));
  END_CPP11
}
// test_interpolate.cpp
int test_interpolate_search(double target, std::vector<double> x);
extern "C" SEXP _dust_test_interpolate_search(SEXP target, SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(test_interpolate_search(cpp11::as_cpp<cpp11::decay_t<double>>(target), cpp11::as_cpp<cpp11::decay_t<std::vector<double>>>(x)));
  END_CPP11
}
// test_interpolate.cpp
double test_interpolate_constant1(std::vector<double> t, std::vector<double> y, double z);
extern "C" SEXP _dust_test_interpolate_constant1(SEXP t, SEXP y, SEXP z) {
  BEGIN_CPP11
    return cpp11::as_sexp(test_interpolate_constant1(cpp11::as_cpp<cpp11::decay_t<std::vector<double>>>(t), cpp11::as_cpp<cpp11::decay_t<std::vector<double>>>(y), cpp11::as_cpp<cpp11::decay_t<double>>(z)));
  END_CPP11
}
// test_interpolate.cpp
double test_interpolate_linear1(std::vector<double> t, std::vector<double> y, double z);
extern "C" SEXP _dust_test_interpolate_linear1(SEXP t, SEXP y, SEXP z) {
  BEGIN_CPP11
    return cpp11::as_sexp(test_interpolate_linear1(cpp11::as_cpp<cpp11::decay_t<std::vector<double>>>(t), cpp11::as_cpp<cpp11::decay_t<std::vector<double>>>(y), cpp11::as_cpp<cpp11::decay_t<double>>(z)));
  END_CPP11
}
// test_interpolate.cpp
double test_interpolate_spline1(std::vector<double> t, std::vector<double> y, double z);
extern "C" SEXP _dust_test_interpolate_spline1(SEXP t, SEXP y, SEXP z) {
  BEGIN_CPP11
    return cpp11::as_sexp(test_interpolate_spline1(cpp11::as_cpp<cpp11::decay_t<std::vector<double>>>(t), cpp11::as_cpp<cpp11::decay_t<std::vector<double>>>(y), cpp11::as_cpp<cpp11::decay_t<double>>(z)));
  END_CPP11
}
// tools.cpp
cpp11::list cpp_scale_log_weights(std::vector<double> w);
extern "C" SEXP _dust_cpp_scale_log_weights(SEXP w) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_scale_log_weights(cpp11::as_cpp<cpp11::decay_t<std::vector<double>>>(w)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_dust_cpp_openmp_info",                (DL_FUNC) &_dust_cpp_openmp_info,                0},
    {"_dust_cpp_scale_log_weights",          (DL_FUNC) &_dust_cpp_scale_log_weights,          1},
    {"_dust_density_beta_binomial",          (DL_FUNC) &_dust_density_beta_binomial,          5},
    {"_dust_density_binomial",               (DL_FUNC) &_dust_density_binomial,               4},
    {"_dust_density_negative_binomial_mu",   (DL_FUNC) &_dust_density_negative_binomial_mu,   5},
    {"_dust_density_negative_binomial_prob", (DL_FUNC) &_dust_density_negative_binomial_prob, 4},
    {"_dust_density_normal",                 (DL_FUNC) &_dust_density_normal,                 4},
    {"_dust_density_poisson",                (DL_FUNC) &_dust_density_poisson,                3},
    {"_dust_test_cuda_pars",                 (DL_FUNC) &_dust_test_cuda_pars,                 9},
    {"_dust_test_interpolate_constant1",     (DL_FUNC) &_dust_test_interpolate_constant1,     3},
    {"_dust_test_interpolate_linear1",       (DL_FUNC) &_dust_test_interpolate_linear1,       3},
    {"_dust_test_interpolate_search",        (DL_FUNC) &_dust_test_interpolate_search,        2},
    {"_dust_test_interpolate_spline1",       (DL_FUNC) &_dust_test_interpolate_spline1,       3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_dust(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
