# Generated by cpp11: do not edit by hand

density_binomial <- function(x, size, prob, log) {
  .Call(`_dust_density_binomial`, x, size, prob, log)
}

density_normal <- function(x, mu, sd, log) {
  .Call(`_dust_density_normal`, x, mu, sd, log)
}

density_negative_binomial_mu <- function(x, size, mu, log, is_float) {
  .Call(`_dust_density_negative_binomial_mu`, x, size, mu, log, is_float)
}

density_negative_binomial_prob <- function(x, size, prob, log) {
  .Call(`_dust_density_negative_binomial_prob`, x, size, prob, log)
}

density_beta_binomial <- function(x, size, prob, rho, log) {
  .Call(`_dust_density_beta_binomial`, x, size, prob, rho, log)
}

density_poisson <- function(x, lambda, log) {
  .Call(`_dust_density_poisson`, x, lambda, log)
}

cpp_openmp_info <- function() {
  .Call(`_dust_cpp_openmp_info`)
}

test_cuda_pars <- function(r_gpu_config, n_particles, n_particles_each, n_state, n_state_full, n_shared_int, n_shared_real, data_size, shared_size) {
  .Call(`_dust_test_cuda_pars`, r_gpu_config, n_particles, n_particles_each, n_state, n_state_full, n_shared_int, n_shared_real, data_size, shared_size)
}

test_interpolate_search <- function(target, x) {
  .Call(`_dust_test_interpolate_search`, target, x)
}

test_interpolate_constant1 <- function(t, y, z) {
  .Call(`_dust_test_interpolate_constant1`, t, y, z)
}

test_interpolate_linear1 <- function(t, y, z) {
  .Call(`_dust_test_interpolate_linear1`, t, y, z)
}

test_interpolate_spline1 <- function(t, y, z) {
  .Call(`_dust_test_interpolate_spline1`, t, y, z)
}

cpp_scale_log_weights <- function(w) {
  .Call(`_dust_cpp_scale_log_weights`, w)
}
